myapp/urls.py
from django.urls import path
app_name="myapp"
from myapp import views
urlpatterns=[
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name='get_demo'),
    path('post_demo/',views.post_demo,name='post_demo'),
    path('register/',views.register,name="registration")
]

p10/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('base/',views.base,name='base'),
    path('home/',views.home,name='home'),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
# Create your views here.
def base(request):
    return render(request,"base.html")
def home(request):
    return render(request,"myapp/home.html")
def profile(request):
    name='ASHOK'
    return render(request,"myapp/profile.html",{'name':name})
def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})

def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1>Thanks for submission Mr./Ms. {} </h1>".format(name))
    return render(request,"post_demo.html")
def register(request):
    if request.method=="POST":
        first_name=request.POST.get('first_name')
        last_name=request.POST.get('last_name')
        email=request.POST.get('email')
        pwd=request.POST.get('pwd')
        phno=request.POST.get('phno')
        date=request.POST.get('birthday_day')
        month=request.POST.get('birthday_month')
        year=request.POST.get('birthday_year')
        gender=request.POST.get('sex')
        if gender=="1":
            gender="Female"
        else:
            gender="Male"
        send_mail("Thanks for Registration","Hello Mr./Ms.{} {}\n Thanks for registering".format(first_name,last_name),"ashokbuengg@gmail.com",[email,],fail_silently=True)
        return HttpResponse("<h1>{}</br>{}</br>{}</br>{}</br>{}</br>{}</br>{}<br>{}</br>{}</br>".format(first_name,last_name,email,pwd,phno,gender,date,month,year))
    return render(request,"myapp/registrationpage.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE HTML</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstarp-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot-min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include "partials/_topbar.html" %}
    {% include "partials/_navbar.html" %}
    {% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome to BASE html</h1>
            <img src="{% static 'images/django_logo.jpg' %}" alt="no image found" height="50" width="30">
        </div>
    </div>
    {% endblock %}
    {% include "partials/_footer.html" %}
</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GET demo</title>
</head>
<body>
    <form method="GET">
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">
    </form>
    <h1>{{name}}</h1>
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}
{% block title %}
    <title>HOME HTML</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to HOME html</h1>
    </div>
</div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}
{% block title %}
    <title>HOME HTML</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to {{name}} PROFILE html</h1>
    </div>
</div>
{% endblock %}

templates/partials/_footer.html
<!--Footer-->
<div class="alert alert-secondary" role="alert">
        <center>Foot Bar</center>
</div>

templates/partials/_navbar.html
    <!--Nav Bar-->
    <div class="container">
        <ul class="nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
            </li>
        </ul>
    </div>

templates/partials/_topbar.html
<!--Top Bar-->
<div class="alert alert-primary" role="alert">
    <center>Top Bar</center>
</div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Demo</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="submit">
    </form>
</body>
</html>